name: Go Tests

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  lint:
    name: Vet Go Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24"

      - name: Run Go Vet
        run: go vet ./...

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24" # Specify your desired Go version

      - name: Install dependencies
        run: |
          go mod tidy
          go mod download

      - name: Run tests
        run: go test -v ./...

  build:
    name: Build Go Application
    runs-on: ubuntu-latest
    needs: [test, lint] # Ensure tests and linting pass before building
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24"

      - name: Install dependencies
        run: |
          go mod tidy
          go mod download

      - name: Build application
        run: go build -v ./...
