name: Go Tests

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  check-changes:
    runs-on: ubuntu-latest
    outputs:
      backend: ${{ steps.changes.outputs.backend }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            backend:
              - '!frontend/**'

  lint-backend:
    name: Vet
    runs-on: ubuntu-latest
    needs: check-changes
    if: needs.check-changes.outputs.backend == 'true'
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24"

      - name: Run Go Vet
        run: go vet ./...

  test-backend:
    name: Test
    runs-on: ubuntu-latest
    needs: check-changes
    if: needs.check-changes.outputs.backend == 'true'
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24"

      - name: Install dependencies
        run: |
          go mod tidy
          go mod download

      - name: Run tests
        run: go test -v ./...

  build-backend:
    name: Build
    runs-on: ubuntu-latest
    needs: [test-backend, lint-backend]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24"

      - name: Install dependencies
        run: |
          go mod tidy
          go mod download

      - name: Build application
        run: go build -v ./...
